#!/usr/bin/env sh

GIT_COLOR="#f14e321"

git_color_text() 
{
  text=$1
  gum style --foreground "$GIT_COLOR" "$text"
}

get_branches() 
{
  if [ ${1+x} ]; then
    # shellcheck disable=SC2046
    gum choose --limit "$1" $(git branch --format="%(refname:short)")
  else
    # shellcheck disable=SC2046
    gum choose --no-limit $(git branch --format="%(refname:short)")
  fi
}

gum style --border normal --margin "1" --padding "1" --border-foreground "$GIT_COLOR" "$(git_color_text " Git") Branch Manager"

printf "%s\n" "Choose $(git_color_text "branches") to operate on" 
branches=$(get_branches)

printf "\n"
printf "%s\n" "Choose a $(git_color_text "command")"
printf "\n"
comm=$(gum choose rebase delete update)

printf "$branches\n" | tr ' ' '\n' | while read branch
do 
  case $comm in 
    rebase)
      base_branch=$(get_branches 1)
      git fetch origin
      git checkout "$branch"
      git rebase "origin/$base_branch"
      ;;

    delete)
      git branch -D "$branch"
      ;;

    update)
      git checkout "$branch"
      git pull --ff-only
      ;;
  esac
done
